baseURL = "https://hshuang.com"
title = "黃宏勝的部落格 | hshuang.com"
locale = "zh-tw"
DefaultContentLanguage = "zh-tw" # Change this to change the site's language
hasCJKLanguage = true
theme = "hugo.386"
preserveTaxonomyNames = true

[params]
    # The name to display as main title in the home page
    mainpagetitle = "HSHuang.com | 黃宏勝的部落格"

    # The subtitle to display under the title in the home page
    mainpagesubtitle = "思考、等待、齋戒、忍耐、傾聽" 

    # The description of your website. It will be displayed in the home page
    mainpagedesc = "2026/09/04：總算是畢業了，但畢業證書只用一個資料夾裝給我，大學的好歹還有燙金證書夾裝著..."

    # The name to display in the copyright section in the footer
    copyrightname = "黃宏勝"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    copyrighturl = ""

    # Show the "built on Hugo" disclaimer
    showhugo = false

    # Urls for social networks
    facebook = ""
    twitter = ""
    linkedin = ""
    github = ""
    gitlab = ""
    rss = "https://hshuang.com/index.xml"

    # Enables or disables the loading animations. false activates them. Default is false.
    loadfastload = false

    # Sets the speed for the page loading effect. Default is 1.0.
    loadspeedfactor = 1.0

    # Enables or disables the second flyby cursor. Default is false.
    loadonepass = false

[params.copyright]
    name = "黃宏勝"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    url = ""

    # Text to go before copyright information
    prefix = ""

    # Text to go between copyright and hugo disclaimer (if enabled)
    suffix = ""

[menu]
  # This displays buttons in the navbar to access your contents
  [[menu.main]]
    identifier = "posts"
    name = "貼文"
    url = "/posts/"       # The path can lead to a content folder too.
    weight = 10
    
  [[menu.main]]
    identifier = "about" # An unique identifier for the button
    name = "關於"       # A display name for the button
    url = "/about/"      # The path to the content. It can lead to a single page (like here)
    weight = 20          # A number to order the buttons in the navbar
    
    [[menu.main]]
    identifier = "now" # An unique identifier for the button
    name = "近況"       # A display name for the button
    url = "/now/"      # The path to the content. It can lead to a single page (like here)
    weight = 30          # A number to order the buttons in the navbar
    
    [[menu.main]]
    identifier = "bucket-list" # An unique identifier for the button
    name = "人生清單"       # A display name for the button
    url = "/bucket-list/"      # The path to the content. It can lead to a single page (like here)
    weight = 40          # A number to order the buttons in the navbar

    [[menu.main]]
    identifier = "books" # An unique identifier for the button
    name = "書單"       # A display name for the button
    url = "/books/"      # The path to the content. It can lead to a single page (like here)
    weight = 50          # A number to order the buttons in the navbar
    
    [[menu.main]]
    identifier = "use" # An unique identifier for the button
    name = "使用"       # A display name for the button
    url = "/use/"      # The path to the content. It can lead to a single page (like here)
    weight = 60          # A number to order the buttons in the navbar
    
    [[menu.main]]
    identifier = "search" # An unique identifier for the button
    name = "搜尋"       # A display name for the button
    url = "/search/"      # The path to the content. It can lead to a single page (like here)
    weight = 70          # A number to order the buttons in the navbar

[taxonomies]
category = "categories"
tag = "tags"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.x]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.x]
    disableInlineCSS = true
